### ISSUE TITLE
Error setting up entry Candy for candy

### ISSUE THREAD

**Issue by kisjeth** [ofalvai/home-assistant-candy#273]
Logger: homeassistant.config_entries
Source: custom_components/candy/__init__.py:54
Integration: Candy (documentation, issues)
First occurred: 16:24:24 (3 occurrences)
Last logged: 16:29:14

Error setting up entry Candy for candy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/candy/__init__.py", line 54, in async_setup_entry
    hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by ofalvai** [comment]
Can you check with the latest Home Assistant version? I'm running `2023.6.2` and I can't reproduce this error.
