### ISSUE TITLE
Where should I put the key?

### ISSUE THREAD

**Issue by hellmind** [ofalvai/home-assistant-candy#57]
I get:

Traceback (most recent call last):
  File "/config/custom_components/candy/client/__init__.py", line 62, in detect_encryption
    assert resp_json.get("response") != "BAD REQUEST"
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/candy/config_flow.py", line 45, in async_step_user
    encryption_type, key = await detect_encryption(
  File "/config/custom_components/candy/client/__init__.py", line 69, in detect_encryption
    async with session.get(url) as resp:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

after I enter the ip
I see no way to enter the key

**Comment by ofalvai** [comment]
Hey @hellmind, I think it's not a problem with the key itself, but the server closes the connection for some reason. We are trying to find a solution for this over at this thread: https://github.com/ofalvai/home-assistant-candy/discussions/53
